periodics:
#  Periodic CI job for running snyk scans against k/k master
# - It installs snyk CLI and requires 'snyk-token' secret available
#   in test infra with key name 'SNYK_TOKEN'. This secret is used to
#   populate env var 'SNYK_TOKEN', required for snyk CLI auth.
# - Licenses and few false positive deps (eg version '0.0.0') are
#   filtered from the snyk scan results.
- name: ci-kubernetes-snyk-master
  interval: 6h
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: sig-security
    base_ref: main
    workdir: true
  spec:
    serviceAccountName: k8s-snyk-scan
    containers:
    - image: golang
      envFrom:
      - secretRef:
          # secret key should be defined as SNYK_TOKEN
          name: snyk-token
      command:
      - sh
      - "-c"
      - "cd sig-security-tooling/scanning/ && ./build-deps-and-release-images.sh"
  annotations:
    testgrid-create-test-group: "true"
    testgrid-alert-email: security-tooling-private@kubernetes.io
    testgrid-num-failures-to-alert: '1'
    testgrid-dashboards: sig-security-snyk-scan
    description: Run snyk scan on k/k master periodically
- name: auto-refreshing-official-cve-feed
  interval: 2h
  cluster: k8s-infra-prow-build-trusted
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: sig-security
    base_ref: main
    workdir: true
  labels:
    preset-service-account: "true"
  spec:
    serviceAccountName: k8s-cve-feed
    containers:
    - image: gcr.io/k8s-staging-test-infra/gcloud-in-go:v20230111-cd1b3caf9c
      command:
      - sh
      - "-c"
      - "cd sig-security-tooling/cve-feed/hack/ && ./fetch-cve-feed.sh"
      env:
      - name: CVE_GCS_PATH
        value: "gs://k8s-cve-feed"
  annotations:
    testgrid-create-test-group: "true"
    testgrid-alert-email: security-tooling-private@kubernetes.io
    testgrid-num-failures-to-alert: '1'
    testgrid-dashboards: sig-security-cve-feed
    description: Auto refreshing official cve feed KEP 3203
